{% set name = "aws-vault" %}
{% set version = "7.9.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ByteNess/aws-vault/releases/download/v{{ version }}/aws-vault-darwin-arm64 # [osx and arm64]
  sha256: 54c7a2cb4862b239b7795e6442e0853d7ba71c7a8403cdbfd6a76128a797fb00 # [osx and arm64]
  url: https://github.com/ByteNess/aws-vault/releases/download/v{{ version }}/aws-vault-linux-amd64 # [linux64 and x86_64]
  sha256: 5917c87f74bacbd4a639830adb75f27c180e75a65ad3d1faef02cf3935c4fd9b # [linux64 and x86_64]

build:
  string: '1'
  binary_relocation: False
  skip: True  # [osx and x86_64]

test:
  commands:
    - aws-vault --version

about:
  home: https://github.com/ByteNess/aws-vault
  license: MIT
  summary: AWS Vault is a tool to securely store and access AWS credentials in a development environment
